#!/bin/bash -x
##
##   BISMON 
##   Copyright © 2018 - 2021 CEA (Commissariat à l'énergie atomique et aux énergies alternatives)
##   contributed by Basile Starynkevitch (working at CEA, LIST, France)
##   <basile@starynkevitch.net> or <basile.starynkevitch@cea.fr>
##
##   This program is free software: you can redistribute it and/or modify
##   it under the terms of the GNU General Public License as published by
##   the Free Software Foundation, either version 3 of the License, or
##   (at your option) any later version.
##
##   This program is distributed in the hope that it will be useful,
##   but WITHOUT ANY WARRANTY; without even the implied warranty of
##   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##   GNU General Public License for more details.
##
##   You should have received a copy of the GNU General Public License
##   along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
##   ----
##   Contact me (Basile Starynkevitch) by email
##   basile@starynkevitch.net and/or basile.starynkevitch@cea.fr
########################################

# the C++ compiler; some GCC (see http://gcc.gnu.org/ ...)
CXX=g++

# the short git id.... 
BISMON_SHGIT1=$(git log --format=oneline -q -1 | cut '-d '  -f1 | tr -d '\n' | head -c16)
BISMON_SHGIT2=$(if git status | grep 'nothing to commit'; then echo; else echo +; fi)
BISMON_SHORT_GIT="$BISMON_SHGIT1$BISMON_SHGIT2"
# Now BISMON_SHORT_GIT could be a string like 6f60bfd0a2dad6bd+ if the
# git repository is dirty, and like 9f60bfd0a2dad6bd if it is clean of
# local changes.

BISMON_CONFIGURE_REAL_PATH=$(realpath $0)
BISMON_CONFIGURE_DIR=$(dirname $BISMON_CONFIGURE_REAL_PATH)
$BISMON_CONFIGURE_DIR/timestamp-emit.sh __timestampconf.c
$CXX -Wall -Wextra -O -g -DBISMON_SHORTGIT=\"$BISMON_SHORT_GIT\" \
     -DBISMON_CONFIG_LABEL=\"from-$BISMON_CONFIGURE_REAL_PATH\" \
     BISMON-config.cc __timestampconf.c -o BISMON-config -lreadline
mv __timestampconf.c __timestampconf.c~

### incomplete
