#!/bin/bash
## FIXME: this should probably becaome a GNU guile script

##   BISMON  ---- simple analysis of the Msh shell
##   Copyright ©  2021 CEA (Commissariat à l'énergie atomique et aux énergies alternatives)
##   contributed by Basile Starynkevitch (working at CEA, LIST, France)
##   <basile@starynkevitch.net> or <basile.starynkevitch@cea.fr>
##
##   This program is free software: you can redistribute it and/or modify
##   it under the terms of the GNU General Public License as published by
##   the Free Software Foundation, either version 3 of the License, or
##   (at your option) any later version.
##
##   This program is distributed in the hope that it will be useful,
##   but WITHOUT ANY WARRANTY; without even the implied warranty of
##   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##   GNU General Public License for more details.
##
##   You should have received a copy of the GNU General Public License
##   along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
##   ----
##   Contact me (Basile Starynkevitch) by email
##   basile@starynkevitch.net and/or basile.starynkevitch@cea.fr
##   -----------

## The Msh shell is a tiny shell whose source code is downloadable
## from git@github.com:nerith/msh.git

## the default source location of Msh could be overidden by the
## BISMON_MSH_SOURCE environment variable
if [ -z "$BISMON_MSH_SOURCE" ]; then
    export BISMON_MSH_SOURCE=/usr/src/Shell/msh/
fi

if [ ! -f "$BISMON_MSH_SOURCE/src/builtins.c" \
	 || ! -f "$BISMON_MSH_SOURCE/src/shellFunctions.c" \
	 || ! -f "$BISMON_MSH_SOURCE/include/shellFunctions.h" ]; then
    printf "%s: invalid MSH source for Bismon %s\n" "$0" "$BISMON_MSH_SOURCE" > /dev/stderr
    exit 1
fi

if [ ! -x bismon ]; then
    ./Build
fi

if [ ! -x bismon ]; then
    printf "%s: missing bismon executable in %s\n" "$0" $(pwd) > /dev/stderr
    exit 1
fi

for f in *.[ch] ; do
    if [ "$f" -nt bismon ]; then
	printf "%s: source file %s newer than bismon executable in %s\n" "$0" "$f" $(pwd) > /dev/stderr
	exit 1
    fi
done

declare -a bismon_msh_args

for f in "$@"; do
    case "$f" in
	--bismon*) bismon_msh_args=($bismon_msh_args $f);;
    esac
done

echo "$0:" bismon arguments $bismon_msh_args in $(pwd) > /dev/stderr

## kill any running bismon
pkill bismon || true


## start a fresh bismon
./bismon $bismon_msh_args &

### missing GCC compilation commands....

### incomplete Msh-Analyze script
printf "%s: incomplete - should run bismon\n" "$0" > /dev/stderr
exit 1
########################################
