#!/bin/bash

##   BISMON  ---- simple analysis of the Msh shell
##   Copyright ©  2021 CEA (Commissariat à l'énergie atomique et aux énergies alternatives)
##   contributed by Basile Starynkevitch (working at CEA, LIST, France)
##   <basile@starynkevitch.net> or <basile.starynkevitch@cea.fr>
##
##   This program is free software: you can redistribute it and/or modify
##   it under the terms of the GNU General Public License as published by
##   the Free Software Foundation, either version 3 of the License, or
##   (at your option) any later version.
##
##   This program is distributed in the hope that it will be useful,
##   but WITHOUT ANY WARRANTY; without even the implied warranty of
##   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##   GNU General Public License for more details.
##
##   You should have received a copy of the GNU General Public License
##   along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
##   ----
##   Contact me (Basile Starynkevitch) by email
##   basile@starynkevitch.net and/or basile.starynkevitch@cea.fr
##   -----------

## The Msh shell is a tiny shell whose source code is downloadable
## from git@github.com:nerith/msh.git

## the default source location of Msh could be overidden by the
## BISMON_MSH_SOURCE environment variable
if [ -z "$BISMON_MSH_SOURCE" ]; then
    export BISMON_MSH_SOURCE=/usr/src/Shell/msh/
fi

if [ ! -f "$BISMON_MSH_SOURCE/src/builtins.c" \
	 || ! -f "$BISMON_MSH_SOURCE/src/shellFunctions.c" \
	 || ! -f "$BISMON_MSH_SOURCE/include/shellFunctions.h" ]; then
    printf "invalid MSH source for Bismon %s\n" "$BISMON_MSH_SOURCE" > /dev/stderr
    exit 1
fi

### incomplete Msh-Analyze script
########################################
