[package]
name = "gtk_rust_bismon"
version = "0.1.0"
edition = "2021"
authors = ["Basile Starynkevitch"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "0.7.0"
gtk = { version = "0.3.0", features = ["v3_22"] }
