#!/bin/bash
# file doc/genscripts/002-gimple-factinline.sh
# this script is running in doc/ directory and extracts the gimple of examples/factinline12.c
echo running genscripts/002-gimple-factinline.sh in $(pwd) 1>&2
source genscripts/cross-gcc-config.bash
cd generated/
rm -vf factinline12.c.0*t.gimple 1>&2
rm -vf factinline12.s 1>&2
$XGCC -O3 -S -fdump-tree-gimple ../examples/factinline12.c  1>&2
(ls -ls $PWD/factinline*) 1>&2
echo "//" factinline12.c.0*t.gimple "generated by ..." >> factinline12.c.0*t.gimple
echo "//... $XGCC C -O3 -S \\" >> factinline12.c.0*t.gimple
echo "//...  -fdump-tree-gimple factinline12.c" >> factinline12.c.0*t.gimple
printf "%%\\lstinputlisting[language=C]{generated/factinline12.c.004t.gimple}\n"
