#!/bin/bash
# file doc/genscripts/002-gimple-factinline.sh
# this script is running in doc/ directory and extracts the gimple of examples/factinline12.c
echo running genscripts/002-gimple-factinline.sh in $(pwd) 1>&2
source genscripts/cross-gcc-config.bash
cd generated/
rm -vf factinline12.c.0*t.gimple 1>&2
rm -vf factinline12-gimple* 1>&2
rm -vf factinline12.s 1>&2
$XGCC -O3 -S -fdump-tree-gimple -fverbose-asm ../examples/factinline12.c  1>&2
(ls -ls $PWD/factinline*) 1>&2
if [ ! -f factinline12.c.0*t.gimple ]; then
    echo missing single 'factinline12.c.0*t.gimple' file > /dev/stderr
fi
echo "//" factinline12.c.0*t.gimple "generated by ..." >> factinline12.c.0*t.gimple
echo "//... $XGCC -O3 -S -fverbose-asm \\" >> factinline12.c.0*t.gimple
echo "//...  -fdump-tree-gimple factinline12.c" >> factinline12.c.0*t.gimple

ln -sv factinline12.c.0*t.gimple factinline12-gimple.c 1>&2

printf '\\begin{table}[h]\n'
printf '\\caption{\\label{tab:factinline} recursive inlining with constant folding in \\emph{GCC}}\n'
printf '   \\medskip\n'
printf '  \\begin{center}\n'
printf '    \\begin{relsize}{-1.5}\n'
printf '     \\begin{tabular}{p{0.85\\textwidth}}\n'
printf '      \\lstinputlisting[language=C]{examples/factinline12.c} \\\\\n'
printf '       %%\\textbf{\\color{blue}{\\emph{C source code}}} \\\\\n'
printf '      \\hline\n'

#awk '/*/{printf "\\verb+%s+ \\\\ \n", $0; next} /\//{printf "\\verb!%s! \\\\ \n", $0; next} //{printf "\\verb/%s/ \\\\ \n", $0; next}' factinline12-gimple.c
printf '      \\\\\n'

#printf '      \\lstinputlisting[language=C]{generated/factinline12-gimple.c} \\\\\n'
printf '       %%\\textbf{\\color{blue}{\\emph{Gimple code}}} \\\\\n'
printf '      \\hline\n'
printf '      \\end{tabular}\n'
printf '    \\end{relsize}\n'
printf '  \\end{center}\n'
printf '\\end{table}\n'

